# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/project/FPGA/My_FPGA/TCL_project/Sim/FFT_sim/user/IP/FFT/FFT.xci
# IP: The module: 'FFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/FPGA/My_FPGA/TCL_project/Sim/FFT_sim/user/IP/FFT/FFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/project/FPGA/My_FPGA/TCL_project/Sim/FFT_sim/user/IP/FFT/FFT.xci
# IP: The module: 'FFT' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/project/FPGA/My_FPGA/TCL_project/Sim/FFT_sim/user/IP/FFT/FFT_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
