// Generated by IP Generator (Version 2016.4B build 16218)


//////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2014 PANGO MICROSYSTEMS, INC
// ALL RIGHTS REVERVED.
//
// THE SOURCE CODE CONTAINED HEREIN IS PROPRIETARY TO PANGO MICROSYSTEMS, INC.
// IT SHALL NOT BE REPRODUCED OR DISCLOSED IN WHOLE OR IN PART OR USED BY
// PARTIES WITHOUT WRITTEN AUTHORIZATION FROM THE OWNER.
//
//////////////////////////////////////////////////////////////////////////////
// Library:
// Filename:dromi_16x512.v
//////////////////////////////////////////////////////////////////////////////

module dromi_16x512 #
(
    parameter    ADDR_WIDTH     =   9,
    parameter    DATA_WIDTH     =   16
)
(
    input   wire    [ADDR_WIDTH-1:0]    addr    ,
    output  reg     [DATA_WIDTH-1:0]    rd_data ,
    input   wire                        clk     ,
     
    input   wire                        clk_en  ,
    input   wire                        rst
);

localparam  DEPTH = 2**ADDR_WIDTH;

reg     [DATA_WIDTH-1:0]  mem [0:DEPTH-1];


initial
begin
    $readmemh("fft_iphase_i.dat",mem,0,DEPTH-1);
end

//always @(posedge clk or posedge rst)
//begin
//    if(rst)
//       rd_data <= {DATA_WIDTH{1'b0}};
//    else if(clk_en)
//       rd_data <=  mem[addr];
//end

always @(posedge clk)
begin
    rd_data <=  mem[addr];
end

endmodule
